services:
  db:
    container_name: postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres #将db这个volume挂到container中的/data/postgres目录
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  zhiconghu-api:
    container_name: zhiconghu-api
    image: zachuaus/zhiconghu-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/customer" #需要连接db container
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
  frontend-react:
    container_name: zachuaus-react
    image: zachuaus/zachuaus-react:latest
    build:
      context: frontend/react # build from local dockerfile
    ports:
     - 3000:5173
    networks:
      - db
    depends_on:
      - zhiconghu-api
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db:
